# Travis installs a "Xenial" dist as default. Travis docs recommends for PHP 7.4 xenial or bionic
dist: bionic
language: php
php:
  - 7.4.1
addons:
  ssh_known_hosts: github.com

jobs:
  include:
    # Declare 2 stages:
    # Stage Validations with 2 jobs (Sniffer, PHPUnit)
    # Stage Deploy with only 1 job
    #- stage: Validations
    #  name: Sniffer
    #  before_script:
    #    - cd app/reports
    #    - sudo apt-get install -y php-codesniffer
    #  script: phpcs -v --extensions=php --standard=PSR2 src/Framework/Controller/ClassPhpCS.php
    #-
    #  name: PHPUnit
    #  before_script:
    #    - cd app/reports && composer install
    #    - wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
    #    - chmod +x phpunit
    #    - ./phpunit --version
    #  script: ./phpunit --bootstrap vendor/autoload.php tests

    - stage: deploy PROD
      env:
        SSH_AUTH_SOCK=/tmp/ssh_agent.sock
      before_script:
        - mkdir -p ~/.ssh
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - cat ~/.ssh/id_rsa
        - ssh-add ~/.ssh/id_rsa
        #- ssh-add - <<< $SSH_PRIVATE_KEY
        #- (umask 077; echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa)

        #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        #- chmod 700 ~/.ssh/id_rsa
        #- eval "$(ssh-agent -s)"
        #- ssh-add ~/.ssh/id_rsa
        #- ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - ls -lrta ~/.ssh/
        - sudo apt-get update
        - sudo apt-get install -y python3-pip && pip3 --version
        - pip3 install Fabric3==1.13.1.post1 && fab --version
        - echo "------Deploying MASTER------"
      script: fab -i /home/travis/.ssh/id_rsa production deploy:env_file="$ENV_FILE_PROD",mysql_env_file="$ENV_MYSQL_FILE"
      if: branch = master

