# Travis installs a "Xenial" dist as default with several packages configured as composer etc.
dist: focal
language: php
rvm:
  - "7.4"

jobs:
  include:
    # Declare 2 stages:
    # Stage Validations with 2 jobs (Sniffer, PHPUnit)
    # Stage Deploy with only 1 job
    - stage: Validations
      name: Sniffer
      language: php
      rvm:
        - "7.4"
      before_script:
        - sudo apt-get -y install php-codesniffer
        - cd app/reports
      script: phpcs -v --extensions=php --standard=PSR2 src/Framework/Controller/ClassPhpCS.php
    -
      name: PHPUnit
      language: php
      rvm:
        - 7.4
      before_script:
        - cd app/reports && composer install
        - wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
        - chmod +x phpunit
        - ./phpunit --version
      script: ./phpunit --bootstrap vendor/autoload.php tests

    #- stage: deploy
    #  before_script:
    #    - apt install -y python3-pip && pip3 --version
    #    - pip3 install Fabric3==1.13.1.post1 && fab --version
    #    - echo "------Deploying MASTER------"
    #  script: fab production deploy:env_file="$ENV_FILE_PROD",mysql_env_file="$ENV_MYSQL_FILE"

